# Generated by Django 5.0.3 on 2024-03-22 13:00

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                null=True, upload_to=product.models.product_image_file_path
            ),
        ),
    ]
