# Generated by Django 5.0.3 on 2024-03-20 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="product.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="features",
            field=models.JSONField(default=list),
        ),
    ]
