# Generated by Django 5.0.3 on 2024-03-20 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_initial"),
        ("product", "0002_alter_category_parent_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="order.order",
            ),
        ),
    ]
