# Generated by Django 5.0.3 on 2024-03-24 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="sale_quantity",
            new_name="capsules_amount",
        ),
    ]
