# Generated by Django 5.0.3 on 2024-03-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="test", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default=380968658843, max_length=15),
            preserve_default=False,
        ),
    ]
